// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkwmvgmauyoozvgcvuat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrd212Z21hdXlvb3p2Z2N2dWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNzg5MTgsImV4cCI6MjA3NTk1NDkxOH0.bs4AcdaHHmmbX6liesu7w2Gfadmc1OibMzKdqnpcB8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});